
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215735;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RouletteTest {
    @Test
    void bulletTest(){
        Roulette rou = new Roulette();
        assertEquals(rou.test,true );
    }
}